name: 'SKonsole Generate PR Description'
description: 'Uses Microsoft SKonsole and Semantic Kernel to update a pull request with an AI generated description.'
inputs:
  target-branch:
    description: "The branch that will be updated with the changes made in the pull request."
    required: true
  source-branch:
    description: "The branch that contains the changes that are being proposed in the pull request."
    required: true
  source-branch-url:
    description: "The URL of the source branch. Required if the branch is in a different repo from the target-branch."
  pull-request-number: 
    description: "The pull request number."
    required: true
  token:
    description: "The GitHub Token to use by this Action (e.g. secrets.GITHUB_TOKEN)"
    required: true
  update-type:
    description: "How to update the PR title/body. Options are 'suffix', 'prefix', and 'replace'. Defaults to 'suffix'"
    default: suffix
runs:
  using: "composite"
  steps:

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target-branch }}
          token: ${{ inputs.token }}
          fetch-depth: 0

      - name: Checkout branches
        run: |
          if [ -z "${{inputs.source-branch-url}}" ]; then
            git checkout ${{inputs.source-branch}}
          else
            git remote add downstream ${{inputs.source-branch-url}}
            git fetch downstream
            git checkout downstream/${{inputs.source-branch}}
          fi
        shell: bash

      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install SKonsole
        run: dotnet tool install --global SKonsole --version 1.0.2
        shell: bash

      - name: Generate PR description  
        id: generate_description
        run: |  
            skonsole pr description --targetBranch ${{ inputs.target-branch }} --outputFormat json --outputFile out.txt
        shell: bash

      - name: Parse PR title
        id: parse_title
        run: echo "pr_title=$(jq -r '.Title' out.txt)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Parse PR summary
        id: parse_summary
        run: echo "pr_summary=$(jq -r '.Summary' out.txt)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Parse PR changes
        id: parse_changes
        run: |
          {
            echo 'pr_changes<<EOF'
            echo "$(jq -r '.Changes[]' out.txt | while read line; do echo "- $line"; done)"
            echo EOF
          } >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Create-Update PR
        uses: mkarle/pr-update@v1
        id: pr_update
        with:
          token: ${{ inputs.token }}
          pr_title:  ${{ steps.parse_title.outputs.pr_title}}
          pr_source: ${{ inputs.source-branch }}
          pr_target: ${{ inputs.target-branch }}
          pr_number: ${{ inputs.pull-request-number }}
          pr_update_type: ${{ inputs.update-type }}
          pr_body: |
            ## Summary
            ${{ steps.parse_summary.outputs.pr_summary }}

            ## Changes
            ${{ steps.parse_changes.outputs.pr_changes }}

            ---
            *Powered by [Microsoft Semantic Kernel](https://github.com/microsoft/semantic-kernel)*
